// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(feature = "eal")]
pub mod eal;
#[cfg(feature = "ethdev")]
pub mod ethdev;
#[cfg(feature = "launch")]
pub mod launch;
#[cfg(feature = "lcore")]
pub mod lcore;
#[cfg(feature = "mbuf")]
pub mod mbuf;
#[cfg(feature = "mempool")]
pub mod mempool;
#[cfg(feature = "thread")]
pub mod thread;
#[cfg(feature = "wrapper")]
pub mod wrapper;
