// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("dpdk_dummy" "C" fn rte_thread_attr_init(attr : *mut rte_thread_attr_t) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_thread_attr_set_priority(thread_attr : *mut rte_thread_attr_t, priority : rte_thread_priority) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_thread_create(thread_id : *mut rte_thread_t, thread_attr : *const rte_thread_attr_t, thread_func : rte_thread_func, arg : *mut core::ffi::c_void) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_thread_create_control(thread : *mut rte_thread_t, name : *const i8, thread_func : rte_thread_func, arg : *mut core::ffi::c_void) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_thread_create_internal_control(id : *mut rte_thread_t, name : *const i8, func : rte_thread_func, arg : *mut core::ffi::c_void) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_thread_detach(thread_id : rte_thread_t) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_thread_equal(t1 : rte_thread_t, t2 : rte_thread_t) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_thread_get_priority(thread_id : rte_thread_t, priority : *mut rte_thread_priority) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_thread_join(thread_id : rte_thread_t, value_ptr : *mut u32) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_thread_key_create(key : *mut rte_thread_key, destructor : *mut isize) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_thread_key_delete(key : rte_thread_key) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_thread_self() -> rte_thread_t);
windows_link::link!("dpdk_dummy" "C" fn rte_thread_set_name(thread_id : rte_thread_t, thread_name : *const i8));
windows_link::link!("dpdk_dummy" "C" fn rte_thread_set_prefixed_name(id : rte_thread_t, name : *const i8));
windows_link::link!("dpdk_dummy" "C" fn rte_thread_set_priority(thread_id : rte_thread_t, priority : rte_thread_priority) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_thread_value_get(key : rte_thread_key) -> *mut core::ffi::c_void);
windows_link::link!("dpdk_dummy" "C" fn rte_thread_value_set(key : rte_thread_key, value : *const core::ffi::c_void) -> i32);
pub const RTE_THREAD_INTERNAL_NAME_SIZE: i32 = 11i32;
pub const RTE_THREAD_NAME_SIZE: i32 = 16i32;
pub const RTE_THREAD_PRIORITY_NORMAL: u32 = 0u32;
pub const RTE_THREAD_PRIORITY_REALTIME_CRITICAL: u32 = 1u32;
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct rte_thread_attr_t {
    pub priority: rte_thread_priority,
}
pub type rte_thread_func =
    Option<unsafe extern "system" fn(param0: *const core::ffi::c_void) -> u32>;
pub type rte_thread_key = *mut core::ffi::c_void;
pub type rte_thread_priority = u32;
#[repr(C, packed(8))]
#[derive(Clone, Copy, Default)]
pub struct rte_thread_t {
    pub opaque_id: u64,
}
