// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("dpdk_dummy" "C" fn rte_eal_cleanup() -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_eal_create_uio_dev() -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_eal_get_baseaddr() -> u64);
windows_link::link!("dpdk_dummy" "C" fn rte_eal_get_runtime_dir() -> *mut i8);
windows_link::link!("dpdk_dummy" "C" fn rte_eal_has_hugepages() -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_eal_has_pci() -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_eal_init(argc : i32, argv : *mut *mut i8) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_eal_iopl_init() -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_eal_iova_mode() -> rte_iova_mode);
windows_link::link!("dpdk_dummy" "C" fn rte_eal_mbuf_user_pool_ops() -> *mut i8);
windows_link::link!("dpdk_dummy" "C" fn rte_eal_primary_proc_alive(config_file_path : *const i8) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_eal_process_type() -> rte_proc_type_t);
windows_link::link!("dpdk_dummy" "C" fn rte_eal_vfio_get_vf_token(vf_token : [ u8 ;16 ]));
windows_link::link!("dpdk_dummy" "C" fn rte_eal_vfio_intr_mode() -> rte_intr_mode);
windows_link::link!("dpdk_dummy" "C" fn rte_gettid() -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_mp_action_register(name : *const i8, action : rte_mp_t) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_mp_action_unregister(name : *const i8));
windows_link::link!("dpdk_dummy" "C" fn rte_mp_disable() -> bool);
windows_link::link!("dpdk_dummy" "C" fn rte_mp_reply(msg : *mut rte_mp_msg, peer : *const i8) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_mp_request_async(req : *mut rte_mp_msg, ts : *const timespec, clb : rte_mp_async_reply_t) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_mp_request_sync(req : *mut rte_mp_msg, reply : *mut rte_mp_reply, ts : *const timespec) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_mp_sendmsg(msg : *mut rte_mp_msg) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_set_application_usage_hook(usage_func : rte_usage_hook_t) -> rte_usage_hook_t);
windows_link::link!("dpdk_dummy" "C" fn rte_sys_gettid() -> i32);
pub const RTE_INTR_MODE_LEGACY: u32 = 1u32;
pub const RTE_INTR_MODE_MSI: u32 = 2u32;
pub const RTE_INTR_MODE_MSIX: u32 = 3u32;
pub const RTE_INTR_MODE_NONE: u32 = 0u32;
pub const RTE_IOVA_DC: u32 = 0u32;
pub const RTE_IOVA_PA: u32 = 1u32;
pub const RTE_IOVA_VA: u32 = 2u32;
pub const RTE_MAGIC: i32 = 19820526i32;
pub const RTE_MP_MAX_FD_NUM: i32 = 253i32;
pub const RTE_MP_MAX_NAME_LEN: i32 = 64i32;
pub const RTE_MP_MAX_PARAM_LEN: i32 = 256i32;
pub const RTE_PROC_AUTO: i32 = -1i32;
pub const RTE_PROC_INVALID: i32 = 2i32;
pub const RTE_PROC_PRIMARY: i32 = 0i32;
pub const RTE_PROC_SECONDARY: i32 = 1i32;
pub const _STRUCT_TIMESPEC: i32 = 1i32;
pub type rte_intr_mode = u32;
pub type rte_iova_mode = u32;
pub type rte_mp_async_reply_t = Option<
    unsafe extern "system" fn(param0: *const rte_mp_msg, param1: *const rte_mp_reply) -> i32,
>;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct rte_mp_msg {
    pub name: [i8; 64],
    pub len_param: i32,
    pub num_fds: i32,
    pub param: [u8; 256],
    pub fds: [i32; 253],
}
impl Default for rte_mp_msg {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct rte_mp_reply {
    pub nb_sent: i32,
    pub nb_received: i32,
    pub msgs: *mut rte_mp_msg,
}
impl Default for rte_mp_reply {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type rte_mp_t = Option<
    unsafe extern "system" fn(param0: *const rte_mp_msg, param1: *const core::ffi::c_void) -> i32,
>;
pub type rte_proc_type_t = i32;
pub type rte_usage_hook_t = Option<unsafe extern "system" fn(param0: *const i8)>;
#[repr(C, packed(8))]
#[derive(Clone, Copy, Default)]
pub struct timespec {
    pub tv_sec: i64,
    pub tv_nsec: i64,
}
