// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn __rte_mbuf_refcnt_update(m : *mut rte_mbuf, value : i16) -> u16);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn __rte_pktmbuf_copy_hdr(mdst : *mut rte_mbuf, msrc : *const rte_mbuf));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn __rte_pktmbuf_free_direct(m : *mut rte_mbuf));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn __rte_pktmbuf_free_extbuf(m : *mut rte_mbuf));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn __rte_pktmbuf_linearize(mbuf : *mut rte_mbuf) -> i32);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn __rte_pktmbuf_pinned_extbuf_decref(m : *mut rte_mbuf) -> i32);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn __rte_pktmbuf_read(m : *const rte_mbuf, off : u32, len : u32, buf : *mut core::ffi::c_void) -> *mut core::ffi::c_void);
windows_link::link!("dpdk_dummy" "C" fn rte_get_rx_ol_flag_list(mask : u64, buf : *mut i8, buflen : u64) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_get_rx_ol_flag_name(mask : u64) -> *mut i8);
windows_link::link!("dpdk_dummy" "C" fn rte_get_tx_ol_flag_list(mask : u64, buf : *mut i8, buflen : u64) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_get_tx_ol_flag_name(mask : u64) -> *mut i8);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_buf_addr(mb : *mut rte_mbuf, mp : *mut super::mempool:: rte_mempool) -> *mut i8);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_check(m : *const rte_mbuf, is_header : i32, reason : *mut *mut i8) -> i32);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_data_addr_default(mb : *mut rte_mbuf) -> *mut i8);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_data_iova(mb : *const rte_mbuf) -> u64);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_data_iova_default(mb : *const rte_mbuf) -> u64);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_dynfield_copy(mdst : *mut rte_mbuf, msrc : *const rte_mbuf));
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_ext_refcnt_read(shinfo : *const rte_mbuf_ext_shared_info) -> u16);
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_ext_refcnt_set(shinfo : *mut rte_mbuf_ext_shared_info, new_value : u16));
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_ext_refcnt_update(shinfo : *mut rte_mbuf_ext_shared_info, value : i16) -> u16);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_from_indirect(mi : *mut rte_mbuf) -> *mut rte_mbuf);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_iova_get(m : *const rte_mbuf) -> u64);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_iova_set(m : *mut rte_mbuf, iova : u64));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_prefetch_part1(m : *mut rte_mbuf));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_prefetch_part2(m : *mut rte_mbuf));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_raw_alloc(mp : *mut super::mempool:: rte_mempool) -> *mut rte_mbuf);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_raw_alloc_bulk(mp : *mut super::mempool:: rte_mempool, mbufs : *mut *mut rte_mbuf, count : u32) -> i32);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_raw_check(m : *const rte_mbuf, mp : *const super::mempool:: rte_mempool, reason : *mut *mut i8) -> i32);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_raw_free(m : *mut rte_mbuf));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_raw_free_bulk(mp : *mut super::mempool:: rte_mempool, mbufs : *mut *mut rte_mbuf, count : u32));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_raw_reset_bulk(mp : *mut super::mempool:: rte_mempool, mbufs : *mut *mut rte_mbuf, count : u32));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_raw_sanity_check(m : *const rte_mbuf, mp : *const super::mempool:: rte_mempool));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_refcnt_read(m : *const rte_mbuf) -> u16);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_refcnt_set(m : *mut rte_mbuf, new_value : u16));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_refcnt_update(m : *mut rte_mbuf, value : i16) -> u16);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_sanity_check(m : *const rte_mbuf, is_header : i32));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_sched_color_get(m : *const rte_mbuf) -> u8);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_sched_color_set(m : *mut rte_mbuf, color : u8));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_sched_get(m : *const rte_mbuf, queue_id : *mut u32, traffic_class : *mut u8, color : *mut u8));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_sched_queue_get(m : *const rte_mbuf) -> u32);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_sched_queue_set(m : *mut rte_mbuf, queue_id : u32));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_sched_set(m : *mut rte_mbuf, queue_id : u32, traffic_class : u8, color : u8));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_sched_traffic_class_get(m : *const rte_mbuf) -> u8);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_sched_traffic_class_set(m : *mut rte_mbuf, traffic_class : u8));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_to_baddr(md : *mut rte_mbuf) -> *mut i8);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_to_priv(m : *mut rte_mbuf) -> *mut core::ffi::c_void);
windows_link::link!("dpdk_dummy" "C" fn rte_mbuf_tx_offload(il2 : u64, il3 : u64, il4 : u64, tso : u64, ol3 : u64, ol2 : u64, unused : u64) -> u64);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_adj(m : *mut rte_mbuf, len : u16) -> *mut i8);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_alloc(mp : *mut super::mempool:: rte_mempool) -> *mut rte_mbuf);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_alloc_bulk(pool : *mut super::mempool:: rte_mempool, mbufs : *mut *mut rte_mbuf, count : u32) -> i32);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_append(m : *mut rte_mbuf, len : u16) -> *mut i8);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_attach(mi : *mut rte_mbuf, m : *mut rte_mbuf));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_attach_extbuf(m : *mut rte_mbuf, buf_addr : *mut core::ffi::c_void, buf_iova : u64, buf_len : u16, shinfo : *mut rte_mbuf_ext_shared_info));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_chain(head : *mut rte_mbuf, tail : *mut rte_mbuf) -> i32);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_clone(md : *mut rte_mbuf, mp : *mut super::mempool:: rte_mempool) -> *mut rte_mbuf);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_copy(m : *const rte_mbuf, mp : *mut super::mempool:: rte_mempool, offset : u32, length : u32) -> *mut rte_mbuf);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_data_room_size(mp : *mut super::mempool:: rte_mempool) -> u16);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_detach(m : *mut rte_mbuf));
#[cfg(all(feature = "ethdev", feature = "lcore", feature = "mempool"))]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_dump(f : *mut super::ethdev:: _IO_FILE, m : *const rte_mbuf, dump_len : u32));
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_ext_shinfo_init_helper(buf_addr : *mut core::ffi::c_void, buf_len : *mut u16, free_cb : rte_mbuf_extbuf_free_callback_t, fcb_opaque : *mut core::ffi::c_void) -> *mut rte_mbuf_ext_shared_info);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_free(m : *mut rte_mbuf));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_free_bulk(mbufs : *mut *mut rte_mbuf, count : u32));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_free_seg(m : *mut rte_mbuf));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_headroom(m : *const rte_mbuf) -> u16);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_init(mp : *mut super::mempool:: rte_mempool, opaque_arg : *mut core::ffi::c_void, m : *mut core::ffi::c_void, i : u32));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_is_contiguous(m : *const rte_mbuf) -> i32);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_lastseg(m : *mut rte_mbuf) -> *mut rte_mbuf);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_linearize(mbuf : *mut rte_mbuf) -> i32);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_pool_create(name : *const i8, n : u32, cache_size : u32, priv_size : u16, data_room_size : u16, socket_id : i32) -> *mut super::mempool:: rte_mempool);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_pool_create_by_ops(name : *const i8, n : u32, cache_size : u32, priv_size : u16, data_room_size : u16, socket_id : i32, ops_name : *const i8) -> *mut super::mempool:: rte_mempool);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_pool_create_extbuf(name : *const i8, n : u32, cache_size : u32, priv_size : u16, data_room_size : u16, socket_id : i32, ext_mem : *const rte_pktmbuf_extmem, ext_num : u32) -> *mut super::mempool:: rte_mempool);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_pool_init(mp : *mut super::mempool:: rte_mempool, opaque_arg : *mut core::ffi::c_void));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_prefree_seg(m : *mut rte_mbuf) -> *mut rte_mbuf);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_prepend(m : *mut rte_mbuf, len : u16) -> *mut i8);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_priv_flags(mp : *mut super::mempool:: rte_mempool) -> u32);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_priv_size(mp : *mut super::mempool:: rte_mempool) -> u16);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_read(m : *const rte_mbuf, off : u32, len : u32, buf : *mut core::ffi::c_void) -> *mut core::ffi::c_void);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_refcnt_update(m : *mut rte_mbuf, v : i16));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_reset(m : *mut rte_mbuf));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_reset_headroom(m : *mut rte_mbuf));
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_tailroom(m : *const rte_mbuf) -> u16);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_pktmbuf_trim(m : *mut rte_mbuf, len : u16) -> i32);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rte_validate_tx_offload(m : *const rte_mbuf) -> i32);
pub const RTE_MBUF_DEFAULT_DATAROOM: i32 = 2048i32;
pub const RTE_MBUF_F_RX_IP_CKSUM_UNKNOWN: i32 = 0i32;
pub const RTE_MBUF_F_RX_L4_CKSUM_UNKNOWN: i32 = 0i32;
pub const RTE_MBUF_F_RX_OUTER_L4_CKSUM_UNKNOWN: i32 = 0i32;
pub const RTE_MBUF_L2_LEN_BITS: u32 = 7u32;
pub const RTE_MBUF_L2_LEN_OFS: u32 = 0u32;
pub const RTE_MBUF_L3_LEN_BITS: u32 = 9u32;
pub const RTE_MBUF_L3_LEN_OFS: u32 = 7u32;
pub const RTE_MBUF_L4_LEN_BITS: u32 = 8u32;
pub const RTE_MBUF_L4_LEN_OFS: u32 = 16u32;
pub const RTE_MBUF_OUTL2_LEN_BITS: u32 = 7u32;
pub const RTE_MBUF_OUTL2_LEN_OFS: u32 = 49u32;
pub const RTE_MBUF_OUTL3_LEN_BITS: u32 = 9u32;
pub const RTE_MBUF_OUTL3_LEN_OFS: u32 = 40u32;
pub const RTE_MBUF_PRIV_ALIGN: i32 = 8i32;
pub const RTE_MBUF_TSO_SEGSZ_BITS: u32 = 16u32;
pub const RTE_MBUF_TSO_SEGSZ_OFS: u32 = 24u32;
pub const RTE_MBUF_TXOFLD_UNUSED_BITS: u32 = 8u32;
pub const RTE_MBUF_TXOFLD_UNUSED_OFS: u32 = 56u32;
pub const _IO_EOF_SEEN: i32 = 16i32;
pub const _IO_ERR_SEEN: i32 = 32i32;
#[repr(C, packed(8))]
#[cfg(all(feature = "ethdev", feature = "lcore"))]
#[derive(Clone, Copy)]
pub struct _IO_FILE {
    pub _flags: i32,
    pub _IO_read_ptr: *mut i8,
    pub _IO_read_end: *mut i8,
    pub _IO_read_base: *mut i8,
    pub _IO_write_base: *mut i8,
    pub _IO_write_ptr: *mut i8,
    pub _IO_write_end: *mut i8,
    pub _IO_buf_base: *mut i8,
    pub _IO_buf_end: *mut i8,
    pub _IO_save_base: *mut i8,
    pub _IO_backup_base: *mut i8,
    pub _IO_save_end: *mut i8,
    pub _markers: *mut core::ffi::c_void,
    pub _chain: *mut super::ethdev::_IO_FILE,
    pub _fileno: i32,
    pub _flags2: i32,
    pub _old_offset: i64,
    pub _cur_column: u16,
    pub _vtable_offset: i8,
    pub _shortbuf: [i8; 1],
    pub _lock: *mut super::lcore::_IO_lock_t,
    pub _offset: i64,
    pub _codecvt: *mut core::ffi::c_void,
    pub _wide_data: *mut core::ffi::c_void,
    pub _freeres_list: *mut super::ethdev::_IO_FILE,
    pub _freeres_buf: *mut core::ffi::c_void,
    pub __pad5: u64,
    pub _mode: i32,
    pub _unused2: [i8; 20],
}
#[cfg(all(feature = "ethdev", feature = "lcore"))]
impl Default for _IO_FILE {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub const _IO_USER_LOCK: i32 = 32768i32;
pub const __struct_FILE_defined: i32 = 1i32;
#[repr(C, packed(64))]
#[cfg(feature = "mempool")]
#[derive(Clone, Copy)]
pub struct rte_mbuf {
    pub buf_addr: *mut core::ffi::c_void,
    pub buf_iova: u64,
    pub ol_flags: u64,
    pub pool: *mut super::mempool::rte_mempool,
    pub next: *mut rte_mbuf,
    pub shinfo: *mut rte_mbuf_ext_shared_info,
    pub priv_size: u16,
    pub timesync: u16,
    pub dynfield1: [u32; 9],
}
#[cfg(feature = "mempool")]
impl Default for rte_mbuf {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct rte_mbuf_ext_shared_info {
    pub free_cb: rte_mbuf_extbuf_free_callback_t,
    pub fcb_opaque: *mut core::ffi::c_void,
    pub refcnt: u16,
}
impl Default for rte_mbuf_ext_shared_info {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type rte_mbuf_extbuf_free_callback_t = Option<
    unsafe extern "system" fn(param0: *const core::ffi::c_void, param1: *const core::ffi::c_void),
>;
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct rte_mbuf_sched {
    pub queue_id: u32,
    pub traffic_class: u8,
    pub color: u8,
    pub reserved: u16,
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct rte_pktmbuf_extmem {
    pub buf_ptr: *mut core::ffi::c_void,
    pub buf_iova: u64,
    pub buf_len: u64,
    pub elt_size: u16,
}
impl Default for rte_pktmbuf_extmem {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct rte_pktmbuf_pool_private {
    pub mbuf_data_room_size: u16,
    pub mbuf_priv_size: u16,
    pub flags: u32,
}
