// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("dpdk_dummy" "C" fn rte_eal_get_lcore_state(worker_id : u32) -> rte_lcore_state_t);
windows_link::link!("dpdk_dummy" "C" fn rte_eal_mp_remote_launch(f : *mut lcore_function_t, arg : *mut core::ffi::c_void, call_main : rte_rmt_call_main_t) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_eal_mp_wait_lcore());
windows_link::link!("dpdk_dummy" "C" fn rte_eal_remote_launch(f : *mut lcore_function_t, arg : *mut core::ffi::c_void, worker_id : u32) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_eal_wait_lcore(worker_id : u32) -> i32);
pub const CALL_MAIN: u32 = 1u32;
pub const RUNNING: u32 = 1u32;
pub const SKIP_MAIN: u32 = 0u32;
pub const WAIT: u32 = 0u32;
pub type lcore_function_t =
    Option<unsafe extern "system" fn(param0: *const core::ffi::c_void) -> i32>;
pub type rte_lcore_state_t = u32;
pub type rte_rmt_call_main_t = u32;
