// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_link::link!("dpdk_dummy" "C" fn rte_eal_lcore_role(lcore_id : u32) -> rte_lcore_role_t);
windows_link::link!("dpdk_dummy" "C" fn rte_get_main_lcore() -> u32);
windows_link::link!("dpdk_dummy" "C" fn rte_get_next_lcore(i : u32, skip_main : i32, wrap : i32) -> u32);
windows_link::link!("dpdk_dummy" "C" fn rte_lcore_callback_register(name : *const i8, init : rte_lcore_init_cb, uninit : rte_lcore_uninit_cb, arg : *mut core::ffi::c_void) -> *mut core::ffi::c_void);
windows_link::link!("dpdk_dummy" "C" fn rte_lcore_callback_unregister(handle : *mut core::ffi::c_void));
windows_link::link!("dpdk_dummy" "C" fn rte_lcore_count() -> u32);
#[cfg(feature = "ethdev")]
windows_link::link!("dpdk_dummy" "C" fn rte_lcore_dump(f : *mut super::ethdev:: _IO_FILE));
windows_link::link!("dpdk_dummy" "C" fn rte_lcore_has_role(lcore_id : u32, role : rte_lcore_role_t) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_lcore_id() -> u32);
windows_link::link!("dpdk_dummy" "C" fn rte_lcore_index(lcore_id : i32) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_lcore_is_enabled(lcore_id : u32) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_lcore_iterate(cb : rte_lcore_iterate_cb, arg : *mut core::ffi::c_void) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_lcore_register_usage_cb(cb : rte_lcore_usage_cb));
windows_link::link!("dpdk_dummy" "C" fn rte_lcore_to_cpu_id(lcore_id : i32) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_lcore_to_socket_id(lcore_id : u32) -> u32);
windows_link::link!("dpdk_dummy" "C" fn rte_socket_count() -> u32);
windows_link::link!("dpdk_dummy" "C" fn rte_socket_id() -> u32);
windows_link::link!("dpdk_dummy" "C" fn rte_socket_id_by_idx(idx : u32) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_thread_register() -> i32);
windows_link::link!("dpdk_dummy" "C" fn rte_thread_unregister());
pub const ROLE_NON_EAL: u32 = 3u32;
pub const ROLE_OFF: u32 = 1u32;
pub const ROLE_RTE: u32 = 0u32;
pub const ROLE_SERVICE: u32 = 2u32;
pub const _IO_EOF_SEEN: i32 = 16i32;
pub const _IO_ERR_SEEN: i32 = 32i32;
#[repr(C, packed(8))]
#[cfg(feature = "ethdev")]
#[derive(Clone, Copy)]
pub struct _IO_FILE {
    pub _flags: i32,
    pub _IO_read_ptr: *mut i8,
    pub _IO_read_end: *mut i8,
    pub _IO_read_base: *mut i8,
    pub _IO_write_base: *mut i8,
    pub _IO_write_ptr: *mut i8,
    pub _IO_write_end: *mut i8,
    pub _IO_buf_base: *mut i8,
    pub _IO_buf_end: *mut i8,
    pub _IO_save_base: *mut i8,
    pub _IO_backup_base: *mut i8,
    pub _IO_save_end: *mut i8,
    pub _markers: *mut core::ffi::c_void,
    pub _chain: *mut super::ethdev::_IO_FILE,
    pub _fileno: i32,
    pub _flags2: i32,
    pub _old_offset: i64,
    pub _cur_column: u16,
    pub _vtable_offset: i8,
    pub _shortbuf: [i8; 1],
    pub _lock: *mut _IO_lock_t,
    pub _offset: i64,
    pub _codecvt: *mut core::ffi::c_void,
    pub _wide_data: *mut core::ffi::c_void,
    pub _freeres_list: *mut super::ethdev::_IO_FILE,
    pub _freeres_buf: *mut core::ffi::c_void,
    pub __pad5: u64,
    pub _mode: i32,
    pub _unused2: [i8; 20],
}
#[cfg(feature = "ethdev")]
impl Default for _IO_FILE {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub const _IO_USER_LOCK: i32 = 32768i32;
pub type _IO_lock_t = isize;
pub const __struct_FILE_defined: i32 = 1i32;
pub type rte_lcore_init_cb =
    Option<unsafe extern "system" fn(param0: u32, param1: *const core::ffi::c_void) -> i32>;
pub type rte_lcore_iterate_cb =
    Option<unsafe extern "system" fn(param0: u32, param1: *const core::ffi::c_void) -> i32>;
pub type rte_lcore_role_t = u32;
pub type rte_lcore_uninit_cb =
    Option<unsafe extern "system" fn(param0: u32, param1: *const core::ffi::c_void)>;
#[repr(C, packed(8))]
#[derive(Clone, Copy, Default)]
pub struct rte_lcore_usage {
    pub total_cycles: u64,
    pub busy_cycles: u64,
}
pub type rte_lcore_usage_cb =
    Option<unsafe extern "system" fn(param0: u32, param1: *const rte_lcore_usage) -> i32>;
