// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(all(feature = "mbuf", feature = "mempool"))]
windows_link::link!("dpdk_dummy" "C" fn rust_eth_rx_burst(port_id : u16, queue_id : u16, rx_pkts : *mut *mut super::mbuf:: rte_mbuf, nb_pkts : u16) -> u16);
#[cfg(all(feature = "mbuf", feature = "mempool"))]
windows_link::link!("dpdk_dummy" "C" fn rust_eth_tx_burst(port_id : u16, queue_id : u16, tx_pkts : *mut *mut super::mbuf:: rte_mbuf, nb_pkts : u16) -> u16);
windows_link::link!("dpdk_dummy" "C" fn rust_get_rte_errno() -> i32);
#[cfg(all(feature = "mbuf", feature = "mempool"))]
windows_link::link!("dpdk_dummy" "C" fn rust_pktmbuf_adj(m : *mut super::mbuf:: rte_mbuf, len : u16) -> *mut i8);
#[cfg(all(feature = "mbuf", feature = "mempool"))]
windows_link::link!("dpdk_dummy" "C" fn rust_pktmbuf_alloc(mp : *mut super::mempool:: rte_mempool) -> *mut super::mbuf:: rte_mbuf);
#[cfg(all(feature = "mbuf", feature = "mempool"))]
windows_link::link!("dpdk_dummy" "C" fn rust_pktmbuf_append(m : *mut super::mbuf:: rte_mbuf, len : u16) -> *mut i8);
#[cfg(all(feature = "mbuf", feature = "mempool"))]
windows_link::link!("dpdk_dummy" "C" fn rust_pktmbuf_data_len(m : *const super::mbuf:: rte_mbuf) -> u16);
#[cfg(feature = "mempool")]
windows_link::link!("dpdk_dummy" "C" fn rust_pktmbuf_data_room_size(mp : *mut super::mempool:: rte_mempool) -> u16);
#[cfg(all(feature = "mbuf", feature = "mempool"))]
windows_link::link!("dpdk_dummy" "C" fn rust_pktmbuf_free(m : *mut super::mbuf:: rte_mbuf));
#[cfg(all(feature = "mbuf", feature = "mempool"))]
windows_link::link!("dpdk_dummy" "C" fn rust_pktmbuf_headroom(m : *const super::mbuf:: rte_mbuf) -> u16);
#[cfg(all(feature = "mbuf", feature = "mempool"))]
windows_link::link!("dpdk_dummy" "C" fn rust_pktmbuf_mtod(m : *mut super::mbuf:: rte_mbuf) -> *mut i8);
#[cfg(all(feature = "mbuf", feature = "mempool"))]
windows_link::link!("dpdk_dummy" "C" fn rust_pktmbuf_pkt_len(m : *const super::mbuf:: rte_mbuf) -> u32);
#[cfg(all(feature = "mbuf", feature = "mempool"))]
windows_link::link!("dpdk_dummy" "C" fn rust_pktmbuf_prepend(m : *mut super::mbuf:: rte_mbuf, len : u16) -> *mut i8);
#[cfg(all(feature = "mbuf", feature = "mempool"))]
windows_link::link!("dpdk_dummy" "C" fn rust_pktmbuf_reset(m : *mut super::mbuf:: rte_mbuf));
#[cfg(all(feature = "mbuf", feature = "mempool"))]
windows_link::link!("dpdk_dummy" "C" fn rust_pktmbuf_set_data_len(m : *mut super::mbuf:: rte_mbuf, len : u16));
#[cfg(all(feature = "mbuf", feature = "mempool"))]
windows_link::link!("dpdk_dummy" "C" fn rust_pktmbuf_set_pkt_len(m : *mut super::mbuf:: rte_mbuf, len : u32));
#[cfg(all(feature = "mbuf", feature = "mempool"))]
windows_link::link!("dpdk_dummy" "C" fn rust_pktmbuf_tailroom(m : *const super::mbuf:: rte_mbuf) -> u16);
#[cfg(all(feature = "mbuf", feature = "mempool"))]
windows_link::link!("dpdk_dummy" "C" fn rust_pktmbuf_trim(m : *mut super::mbuf:: rte_mbuf, len : u16) -> i32);
windows_link::link!("dpdk_dummy" "C" fn rust_rte_get_main_lcore() -> u32);
windows_link::link!("dpdk_dummy" "C" fn rust_rte_lcore_id() -> u32);
windows_link::link!("dpdk_dummy" "C" fn rust_set_rte_errno(err : i32));
